import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html>
            <body>
                <nav>
                    <Link href="/about">About</Link>
                    <Link href="/resume">Resume</Link>
                    <Link href="/blog">Blog</Link>
                    <a href="https://github.com/cmathews393">Github</a>
                    <a href="https://linkedin.com/in/cmathews393">LinkedIn</a>
                </nav>
                {children}
            </body>
        </html>
    );
}
